name: Continuous Integration

on:
  push:
    tags:
      - 'v*.*.*'  # Executa o release apenas com push de tags versionadas (ex: v1.0.0)
  pull_request:
    branches:
      - main  # Valida commits nos PRs direcionados para a branch main

jobs:
  validate-commits:
    name: Validação de Commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Só roda para PRs

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          fetch-tags: true

      - name: Buscar o histórico completo de todas as branches
        run: git fetch --all

      - name: Verificar mensagens de commit
        run: |
          commits=$(git log origin/main..${{ github.head_ref }} --pretty=format:"%s")
          echo "$commits" | while read line; do
            if ! echo "$line" | grep -Eq "^(feat|fix|chore|docs|style|refactor|perf|test)(\(.+\))?: .+"; then
              echo "::error file=COMMIT_MESSAGE::❌ Commit inválido: '$line'"
              echo ""
              echo "🔧 Use o padrão: <tipo>(escopo opcional): descrição breve"
              echo "Exemplos válidos:"
              echo " - feat(login): adiciona autenticação"
              echo " - fix(api): corrige retorno de erro 500"
              exit 1
            fi
          done
          echo "✅ Todos os commits estão válidos."

  changelog:
    name: Gerar Changelog
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions: 
      contents: write

    steps:
      - name: Verificar código
        uses: actions/checkout@v2
        
      - name: Configurar Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Instalar auto-changelog
        run: | 
          npm install -g auto-changelog 

      - name: Descobrir tag anterior
        id: previous_tag
        run: |
          tag=$(git describe --tags --abbrev=0 HEAD^ || echo "")
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
      - name: Gerar Changelog
        run: |
          if [ -z "${{ steps.previous_tag.outputs.tag }}" ]; then
            echo "🔄 Nenhuma tag anterior encontrada. Gerando changelog completo..."
            npx auto-changelog --commit-limit false
          else
            echo "🔄 Gerando changelog desde a tag: ${{ steps.previous_tag.outputs.tag }}"
            npx auto-changelog --starting-version ${{ steps.previous_tag.outputs.tag }} --commit-limit false
          fi

      - name: Verificar conteúdo do diretório após gerar changelog
        run: |
          echo "Conteúdo da pasta após geração:"
          ls -lah
          echo "Conteúdo do CHANGELOG.md:"
          cat CHANGELOG.md || echo "❌ CHANGELOG.md não encontrado!"

      - name: Criar branch de changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore: gerar changelog para ${{ github.ref_name }}"
          git checkout -b chore/changelog-${{ github.ref_name }}
          git push origin chore/changelog-${{ github.ref_name }}

      - name: Criar Pull Request com o changelog
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/changelog-${{ github.ref_name }}
          base: test/conventional-commits
          commit-message: 'chore: gerar changelog para ${{ github.ref_name }}'
          title: 'chore: changelog para ${{ github.ref_name }}'
          body: 'Este PR inclui o changelog gerado automaticamente para `${{ github.ref_name }}`.'
          labels: changelog
        